MvcOOPHamburgerProject/Models/OurMenuViewModel.cs
using MvcOOPHamburgerProject.Data.Entities.Concrete;

namespace MvcOOPHamburgerProject.Models
{
    public class OurMenuViewModel
    {
        public List<Product>? Products { get; set; }
        public List<Category>? Categories { get; set; }
        public List<Menu>? Menus { get; set; } 
        public int? SelectedCategoryId { get; set; }
    }
}

MvcOOPHamburgerProject/Areas/Admin/Controllers/TestimonialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcOOPHamburgerProject.Data.Context;
using MvcOOPHamburgerProject.Data.Entities.Concrete;

namespace MvcOOPHamburgerProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TestimonialsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TestimonialsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Testimonials
        public async Task<IActionResult> Index()
        {
            return View(await _context.Testimonials.ToListAsync());
        }

        // GET: Admin/Testimonials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testimonial = await _context.Testimonials
                .FirstOrDefaultAsync(m => m.Id == id);
            if (testimonial == null)
            {
                return NotFound();
            }

            return View(testimonial);
        }

        // GET: Admin/Testimonials/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Testimonials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Puan,ImageUrl")] Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testimonial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(testimonial);
        }

        // GET: Admin/Testimonials/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testimonial = await _context.Testimonials.FindAsync(id);
            if (testimonial == null)
            {
                return NotFound();
            }
            return View(testimonial);
        }

        // POST: Admin/Testimonials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Puan,ImageUrl")] Testimonial testimonial)
        {
            if (id != testimonial.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testimonial);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestimonialExists(testimonial.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(testimonial);
        }

        // GET: Admin/Testimonials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testimonial = await _context.Testimonials
                .FirstOrDefaultAsync(m => m.Id == id);
            if (testimonial == null)
            {
                return NotFound();
            }

            return View(testimonial);
        }

        // POST: Admin/Testimonials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var testimonial = await _context.Testimonials.FindAsync(id);
            if (testimonial != null)
            {
                _context.Testimonials.Remove(testimonial);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestimonialExists(int id)
        {
            return _context.Testimonials.Any(e => e.Id == id);
        }
    }
}

MvcOOPHamburgerProject/ViewComponents/AboutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcOOPHamburgerProject.Data.Context;

namespace MvcOOPHamburgerProject.ViewComponents
{
    public class AboutViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public AboutViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _db.Abouts.ToListAsync());
        }
    }
}

MvcOOPHamburgerProject/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcOOPHamburgerProject.Data.Context;

namespace MvcOOPHamburgerProject.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public CategoriesViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()  
        {
            return View(await _db.Categories.ToListAsync());
        }
    }
}

MvcOOPHamburgerProject/ViewComponents/ContactViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcOOPHamburgerProject.Data.Context;

namespace MvcOOPHamburgerProject.ViewComponents
{
    public class ContactViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public ContactViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MvcOOPHamburgerProject/ViewComponents/TestimonialViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcOOPHamburgerProject.Data.Context;

namespace MvcOOPHamburgerProject.ViewComponents
{
    public class TestimonialViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public TestimonialViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _db.Testimonials.ToListAsync());
        }
    }
}

MvcOOPHamburgerProject/Views/Home/About.cshtml
@model List<About>
@{
    ViewData["Title"] = "About";
}

<!--Header-->
<partial name="_Header" />
<!--About-->
<section class="about_section layout_padding">
    <div class="container">
    <h2 class=" text-secondary fw-light">About Us</h2>
    <hr />
    <div class="row">
        @foreach (var item in Model)
        {
            <div>
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="~/customer/images/@item.ImageUrl" class="img-fluid rounded-start" alt="icon" />
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">@item.Title</h5>
                                <p class="card-text">@item.Description</p>
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    </div>
    <hr />
</section>
<!--Header-->
<partial name="_Footer" />

MvcOOPHamburgerProject/Views/Home/Card.cshtml
@model MvcOOPHamburgerProject.Data.Entities.Concrete.Order

@{
    ViewData["Title"] = "Card";
}
<partial name="_Header" />
<style>
    .order_section {
        padding: 20px;
    }

    .order-card {
        background-color: #192a56;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        color: #fff; /* Yazı rengi beyaz */
        padding: 20px;
        margin: 20px;
    }

        .order-card h4,
        .order-card h6 {
            background-color: rgba(255, 215, 0, 0.7);
        }

        .order-card table th {
            background-color: darkred;
            color: #fff; 
        }

</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<section class="order_section">
    <div class="container">
        <div class="order-card">
            <div>
                <h4>Your Card</h4>
                <h6>Order ID: @Model.Id</h6>
                <h6>Date: @Model.Date</h6>
                <h6>Status: @Model.Status</h6>

                <h3>Order Items:</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.OrderDetails)
                        {
                            <tr>
                                <td>
                                    @if (item.Product != null)
                                    {
                                        @item.Product.Name
                                    }
                                    else if (item.Menu != null)
                                    {
                                        @item.Menu.Name
                                    }
                                </td>
                                <td>
                                    <div>
                                        @item.Quantity
                                    </div>
                                </td>
                                <td>
                                    @item.TotalPrice.ToString("C2")
                                </td>
                                <td>
                                    <form asp-area="" asp-controller="Home" asp-action="DeleteOrderDetail" method="post">
                                        <button class="btn btn-danger" type="submit" name=orderDetailId value="@item.Id"><i class="fa-solid fa-trash"></i></button>
                                    </form>
                                    <form asp-area="" asp-controller="Home" asp-action="EditOrderDetail" method="get">
                                        <button class="btn btn-success" type="submit" name="orderDetailId" value="@item.Id" data-toggle="modal" data-target="#editOrderDetailModal"><i class="fa-solid fa-pen"></i></button>
                                    </form>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td colspan="2">Total Price :</td>
                            <td>@Model.TotalPrice.ToString("C2")</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<div class="form-group mb-3">
    @if (Model.Status == OrderStatus.Pending)
    {
        <form asp-area="" asp-controller="Home" asp-action="ConfirmOrder" method="post">
            <button type="submit" name="orderId" value="@Model.Id" class="btn btn-primary">Confirm Order</button>
        </form>
    }
    else if (Model.Status == OrderStatus.Confirmed)
    {
        <form asp-area="" asp-controller="Home" asp-action="CancelOrder" method="post">
            <button type="submit" name="orderId" value="@Model.Id" class="btn btn-primary">Cancel Order</button>
        </form>
    }
    else if (Model.Status == OrderStatus.Ready)
    {
        Model.Status = OrderStatus.Ready;
        <button type="submit" name="orderId" onclick="openEditOrderDetailModal()" value="@Model.Id" class="btn btn-primary" hidden></button>
    }
</div>
<partial name="_Footer" />
@section Scripts {
    <script>
        // Show toastr messages
        $(document).ready(function () {
            var successMessage = '@TempData["SuccessMessage"]';
            var errorMessage = '@TempData["ErrorMessage"]';

            if (successMessage) {
                toastr.success(successMessage);
            }

            if (errorMessage) {
                toastr.error(errorMessage);
            }
        });

        // Function to show notifications when Model.Status changes
        function showNotification(status) {
            switch (status) {
                case 'Confirmed':
                    toastr["success"]("Your order has been confirmed.");
                    break;
                case 'Cancelled':
                    toastr["error"]("Your order has been cancelled.");
                    break;
                case 'Ready':
                    toastr["info"]("Your order is being prepared.");
                    break;
                default:
                    break;
            }
        }

        // Show notification for the current Model.Status when the page is loaded
        $(document).ready(function () {
            showNotification('@Model.Status');
        });

        function openEditOrderDetailModal() {
            $('#editOrderDetailModal').modal('show');
        }

    </script>
}

MvcOOPHamburgerProject/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<!--Header-->
<partial name="_Header" />
<!--Contact-->
<vc:contact />
<!--Footer-->
<partial name="_Footer" />

MvcOOPHamburgerProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!--Header-->
    <partial name="_HeaderWithSlider" />
<div class="container mb-5 mt-5">
    <!--Category-->
    <div class="mb-3">
    <vc:categories/>
    </div>
    <!--About-->
    <div class="home-box mt-5 mb-3">
        <vc:about />
    </div>
    <!--OurMenu-->
    <!--Testimonial-->
    <vc:testimonial />
    <!--Contact-->
    <div class="home-box mb-3">
    <vc:contact />
    </div>
</div>
<!--Footer-->
<partial name="_Footer" />

MvcOOPHamburgerProject/Views/Home/OurMenu.cshtml
@{
    ViewData["Title"] = "OurMenu";
}

MvcOOPHamburgerProject/Views/Home/Testimonial.cshtml
@{
    ViewData["Title"] = "Testimonial";
}

<!--Header-->
<partial name="_Header" />
<!--Testimonial-->
<vc:testimonial />
<!--Footer-->
<partial name="_Footer" />